/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;

/**
 *
 * @author aome1
 */
public class MenuPanel extends javax.swing.JPanel {

    private boolean showing = false;
    private ActionListener action;
    public ArrayList<MenuPanel> getSubMenu() {
        return subMenu;
    }

    private final ArrayList<MenuPanel> subMenu = new ArrayList<>();
    
    /**
     * Creates new form MenuPanel
     * @param icon
     * @param menuName
     * @param subMenu
     */
    public MenuPanel(Icon icon,String menuName, ActionListener action, MenuPanel...subMenu) {
        initComponents();
        jLabelIcon.setIcon(icon);
        jLabelName.setText(menuName);
        
        // actionListener
        if(action != null)
        {
            this.action = action;
        }
        
        
        // dimension
        this. setSize(new Dimension(Integer.MAX_VALUE,50));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE,50));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE,50));
        
        // array of sub menu items
        for(int i = 0; i< subMenu.length; i++)
        {
            this.subMenu. add(subMenu[i]);
                
            // ubMenu[i].setVisible(false);
            subMenu[i].setVisible(false);
            //hideMenu();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabelIcon = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelName.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabelIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         // TODO add your handling code here:
         if(showing)
         {
             // calles the hideMenu Method
             hideMenu(this);
             showing = false;
         }
       
         else
         {
             // calls the showMenu Method
             showMenu();
             showing = true;
         }
         
         //action Listener
         if(action != null)
         {
             action.actionPerformed(null); 
         }
                 
         
    }//GEN-LAST:event_formMousePressed
    // Method: Show manu 
    private void showMenu()
    {
        new Thread(() -> {
            for(int i = 0; i< subMenu.size(); i++)
            {
                // calles the method sleep
                sleep();
                
                subMenu.get(i).setVisible(true);
            }
            
        }).start();
    }
    // Method: Hide Menu 
    private void hideMenu(MenuPanel menu)
    {
            new Thread(() -> {
                ArrayList<MenuPanel> subMenu = menu.getSubMenu();
                for(int i = subMenu.size()-1; i>= 0; i--)
                {
                    // called the method sleep
                    sleep();
                    
                    subMenu.get(i).setVisible(false);
                    hideMenu(subMenu.get(i));
                }
            }).start();
    }
    
    private void sleep()
    {
        try 
        {
            Thread.sleep(20);
        }
        catch (InterruptedException e) 
        {
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables



}
